# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
